# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for english-coach GUI (v0.9.4)
# Build: pyinstaller english_coach.spec

import sys
import os
from pathlib import Path

block_cipher = None

_WEBVIEW = r'C:\Users\XINGLUOYUNSHEN\AppData\Roaming\Python\Python313\site-packages\webview'

_PYTHONNET = r'C:\Users\XINGLUOYUNSHEN\AppData\Roaming\Python\Python313\site-packages\pythonnet'

# Make Python.Runtime.dll discoverable by the old hook-clr.py
# by adding its directory to PATH before Analysis runs
_pyruntime_dir = str(Path(_PYTHONNET) / 'runtime')
os.environ['PATH'] = _pyruntime_dir + os.pathsep + os.environ.get('PATH', '')

a = Analysis(
    ['gui/main.py'],
    pathex=['.'],
    binaries=[
        (f'{_WEBVIEW}\\lib\\Microsoft.Web.WebView2.Core.dll',   'webview\\lib'),
        (f'{_WEBVIEW}\\lib\\Microsoft.Web.WebView2.WinForms.dll','webview\\lib'),
        (f'{_WEBVIEW}\\lib\\WebBrowserInterop.x64.dll',         'webview\\lib'),
        (f'{_WEBVIEW}\\lib\\WebBrowserInterop.x86.dll',         'webview\\lib'),
        (f'{_PYTHONNET}\\runtime\\Python.Runtime.dll',          'pythonnet\\runtime'),
    ],
    datas=[
        ('config.yaml', '.'),
        ('content', 'content'),
        ('gui/static', 'gui/static'),
        (f'{_WEBVIEW}\\js', 'webview\\js'),
        (f'{_WEBVIEW}\\lib\\runtimes', 'webview\\lib\\runtimes'),
        (f'{_PYTHONNET}\\runtime\\Python.Runtime.deps.json', 'pythonnet\\runtime'),
    ],
    hiddenimports=[
        # Core app
        'openai',
        'edge_tts',
        'rich',
        'typer',
        'yaml',
        'frontmatter',
        'sqlite3',
        'core.ingestion.pipeline',
        'core.knowledge_base.store',
        'core.srs.engine',
        'core.user_model.profile',
        'ai.client',
        'ai.tts',
        'modes.vocab',
        'modes.reading',
        'modes.writing',
        'modes.speaking',
        'modes.grammar',
        'modes.chat',
        'modes.plan',
        'modes.words',
        'modes.notebook',
        'modes.mock_exam',
        'modes.lookup',
        'modes.anki_export',
        'modes.users',
        'modes.packs',
        'cli.display',
        # GUI
        'fastapi',
        'fastapi.staticfiles',
        'fastapi.responses',
        'uvicorn',
        'uvicorn.__main__',
        'uvicorn._compat',
        'uvicorn._subprocess',
        'uvicorn._types',
        'uvicorn.config',
        'uvicorn.importer',
        'uvicorn.lifespan',
        'uvicorn.lifespan.off',
        'uvicorn.lifespan.on',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.asyncio',
        'uvicorn.loops.auto',
        'uvicorn.loops.uvloop',
        'uvicorn.main',
        'uvicorn.middleware',
        'uvicorn.middleware.asgi2',
        'uvicorn.middleware.message_logger',
        'uvicorn.middleware.proxy_headers',
        'uvicorn.middleware.wsgi',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.flow_control',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.utils',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.protocols.websockets.websockets_sansio_impl',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.server',
        'uvicorn.supervisors',
        'uvicorn.supervisors.basereload',
        'uvicorn.supervisors.multiprocess',
        'uvicorn.supervisors.statreload',
        'uvicorn.supervisors.watchfilesreload',
        'uvicorn.workers',
        'starlette',
        'starlette._exception_handler',
        'starlette._utils',
        'starlette.applications',
        'starlette.authentication',
        'starlette.background',
        'starlette.concurrency',
        'starlette.config',
        'starlette.convertors',
        'starlette.datastructures',
        'starlette.endpoints',
        'starlette.exceptions',
        'starlette.formparsers',
        'starlette.middleware',
        'starlette.middleware.authentication',
        'starlette.middleware.base',
        'starlette.middleware.cors',
        'starlette.middleware.errors',
        'starlette.middleware.exceptions',
        'starlette.middleware.gzip',
        'starlette.middleware.httpsredirect',
        'starlette.middleware.sessions',
        'starlette.middleware.trustedhost',
        'starlette.middleware.wsgi',
        'starlette.requests',
        'starlette.responses',
        'starlette.routing',
        'starlette.schemas',
        'starlette.staticfiles',
        'starlette.status',
        'starlette.templating',
        'starlette.types',
        'starlette.websockets',
        'anyio',
        'anyio._backends._asyncio',
        'anyio._backends._trio',
        'webview',
        'webview.platforms.edgechromium',
        'webview.platforms.mshtml',
        'webview.platforms.winforms',
        'webview.guilib',
        'webview.http',
        'webview.util',
        'webview.window',
        'webview.screen',
        'webview.menu',
        'webview.dom',
        'webview.event',
        'webview.errors',
        'webview.localization',
        'webview.state',
        'webview.models',
        'gui.server',
        'gui.deps',
        'gui.api.vocab',
        'gui.api.grammar',
        'gui.api.reading',
        'gui.api.writing',
        'gui.api.chat',
        'gui.api.progress',
        'gui.api.setup',
        'gui.api.license',
        'gui.api.history',
        'gui.api.voice',
        'gui.api.listening',
        'gui.api.wordbooks',
        'gui.api.warehouse',
        'gui.license',
        'pydantic',
        'h11',
        'sse_starlette',
        'pkg_resources.py2_warn',
        'pkg_resources.markers',
        # pythonnet / clr (required by pywebview on Windows)
        'pythonnet',
        'clr',
        'clr._extras',
        'clr.interop',
        'clr_loader',
        'clr_loader.ffi',
        'clr_loader.ffi.hostfxr',
        'clr_loader.ffi.mono',
        'clr_loader.ffi.netfx',
        'clr_loader.hostfxr',
        'clr_loader.mono',
        'clr_loader.netfx',
        'clr_loader.types',
        'clr_loader.util',
        'clr_loader.util.clr_error',
        'clr_loader.util.coreclr_errors',
        'clr_loader.util.find',
        'clr_loader.util.hostfxr_errors',
        'clr_loader.util.runtime_spec',
    ],
    hookspath=['hooks'],
    runtime_hooks=[],
    excludes=[
        # Large ML/AI libraries (not used)
        'chromadb',
        'sentence_transformers',
        'torch',
        'transformers',
        'numpy',
        'pandas',
        'matplotlib',
        'tkinter',
        'faster_whisper',
        'ctranslate2',
        'av',
        # Additional exclusions for faster startup
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='english-coach',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
